// @ts-nocheck
/** Central app state (legacy shape; gradual typing later). */
export const state = {
  baseUrl: "",
  token: "",
  user: null,
  authMode: "login",
  hasSearched: false,
  searchDebounceTimer: null,
  lastSearchQuery: "",
  searchRequestSeq: 0,
  searchAbortController: null,
  /** Max songs to render in search ( grows with "Load more" ). */
  searchSongVisibleLimit: 100,
  /** Current primary view id (for skipping expensive renders when hidden). */
  activeViewId: "",
  searchResults: [],
  searchFilter: "songs",
  playlists: [],
  discoveredPlaylists: [],
  followingPlaylists: [],
  activePlaylistTab: "owned",
  selectedPlaylistId: null,
  selectedPlaylistDetail: null,
  selectedPlaylistIsOwned: false,
  syncTimer: null,
  socialSyncTimer: null,
  lastKnownPlaylistUpdatedAt: null,
  favorites: [],
  history: [],
  topArtists: [],
  recommendations: [],
  selectedArtistName: "",
  artistDetailResults: [],
  artistDetailTab: "songs",
  artistDetailSource: "fallback",
  artistDetailArtworkUrl: "",
  artistSongsLimit: 10_000,
  artistSongsTotalAvailable: 0,
  /** False while only iTunes lookup songs are shown; full album merge still pending. */
  artistDetailCatalogComplete: true,
  artistDetailFilterQuery: "",
  artistAlbums: [],
  selectedArtistAlbum: null,
  artistAlbumTracks: [],
  currentPlayingSong: null,
  lastHistorySentMs: 0,
  playedAccumulatedMs: 0,
  lastPlayStartedAtMs: null,
  isHistoryPosting: false,
  actionLocks: new Set(),
  serviceWorkerReady: false,
  queue: [],
  queueIndex: -1,
  queueDragFromIndex: null,
  repeatQueue: false,
  repeatSong: false,
  shuffleQueue: false,
  audioPrefs: {
    volume: 0.9,
  },
  uiPrefs: {
    sidebarCollapsed: false,
    playerHidden: false,
    fullPlayerOpen: false,
  },
  activeFpTab: "related",
  fullPlayerMediaMode: "song",
  /** Discover Play: full-player video element carries audio (not audioPlayer preview). */
  playbackVideoPrimary: null,
  favoriteTogglePending: null,
  librarySummary: null,
  libraryStats: null,
  analytics: {
    days: 30,
    limit: 10,
    topTracks: [],
    topGenres: [],
    initialFetchComplete: false,
  },
  trendingTracks: [],
  trendingFetchComplete: false,
  browseGenreName: "",
  browseGenreTracks: [],
  browseGenreTracksLimit: 0,
  browseGenreLoading: false,
  historyFilters: {
    source: "all",
    period: "all",
  },
  songRelationsCache: new Map(),
  libraryCollections: {
    artists: [],
    albums: [],
  },
  libraryArtworkCache: {
    artists: new Map(),
    albums: new Map(),
  },
  socialFollowingUsers: [],
  artistListenerProfiles: [],
  artistListenerArtistName: "",
  artistListenerCache: new Map(),
  artistArtworkCache: new Map(),
  failedArtistArtworkUrls: new Set(),
  searchProfilesMode: "listeners",
  selfProfilePlaylists: [],
  userProfileUsername: "",
  userProfileAvatarUrl: "",
  userProfileBio: "",
  userProfileFollowedAt: "",
  userProfilePlaylists: [],
  userProfileBackView: "followingUsersView",
  selectedFollowingUsername: "",
  selectedFollowingUserPlaylists: [],
  followingUserPlaylistsCache: new Map(),
  profilePrefs: {
    avatarUrl: "",
    bio: "",
  },
  responsiveViewportMode: "",
  artistSongsPage: 0,
  artistAlbumsPage: 0,
  artistSongsSlideDir: "",
  artistAlbumsSlideDir: "",
  syncSession: {
    sessionId: null,
    isHost: false,
    ws: null,
  },
  syncPlaybackBlocked: false,
  dataRefreshTimer: null,
  dataRefreshHeavyTimer: null,
  dataRefreshLightInFlight: false,
  dataRefreshHeavyInFlight: false,
  dataRefreshFullInFlight: false,
  /** True while login/boot `refreshAllData` runs; blocks overlapping background polls. */
  dataRefreshBulkInFlight: false,
  docHiddenAtMs: null,
  /** Discover (Reels) samples from GET /discover/feed or /discover/saved */
  discoverSamples: [],
  /** Cached main feed when switching to Saved tab */
  discoverForYouSamples: [],
  /** "forYou" | "saved" */
  discoverListMode: "forYou",
  discoverActiveIndex: 0,
  /** When opening from #discover/{id}, applied on next feed load */
  discoverPendingSampleId: null,
  /** User mute for reel player; kept across reel changes, cleared when leaving Discover */
  discoverReelMuted: false,
  /** Sample videos for current artist detail page */
  artistDiscoverVideos: [],
  /** Snapshot of uiPrefs.playerHidden before opening Discover; restored when leaving */
  playerHiddenBeforeDiscover: null,
};
